//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mad.analyzers.common {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MadAnalyzerCodeQualityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MadAnalyzerCodeQualityResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mad.analyzers.common.MadAnalyzerCodeQualityResources", typeof(MadAnalyzerCodeQualityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exceptions should be passed as first parameter for the stacktrace to be available in the logs. ähnelt.
        /// </summary>
        public static string MAD1312_Description {
            get {
                return ResourceManager.GetString("MAD1312_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exceptions should be passed as the first parameter to the log call. ähnelt.
        /// </summary>
        public static string MAD1312_Message {
            get {
                return ResourceManager.GetString("MAD1312_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PassExceptionAsFirstParameter ähnelt.
        /// </summary>
        public static string MAD1312_Title {
            get {
                return ResourceManager.GetString("MAD1312_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A named placeholder used with ILogger should be PascalCase, a naming convention where the first letter of each compound word in a name is capitalized. This naming convention is recommended for structured logging, where each named placeholder is used as a property name in the structured data. ähnelt.
        /// </summary>
        public static string MAD1727_Description {
            get {
                return ResourceManager.GetString("MAD1727_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use PascalCase for named placeholders ähnelt.
        /// </summary>
        public static string MAD1727_Message {
            get {
                return ResourceManager.GetString("MAD1727_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UsePascalCaseForNamedPlaceholders ähnelt.
        /// </summary>
        public static string MAD1727_Title {
            get {
                return ResourceManager.GetString("MAD1727_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of parameters supplied to the logging method should match the number of placeholders contained in the log message. ähnelt.
        /// </summary>
        public static string MAD2017_Description {
            get {
                return ResourceManager.GetString("MAD2017_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template parameter count does not match with supplied parameters. Expected {0} but got {1}. ähnelt.
        /// </summary>
        public static string MAD2017_Message {
            get {
                return ResourceManager.GetString("MAD2017_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ParameterCountMismatch ähnelt.
        /// </summary>
        public static string MAD2017_Title {
            get {
                return ResourceManager.GetString("MAD2017_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging message templates use curly braces { and } to denote named placeholders for values. Invalid brace usage in message templates can result in runtime exceptions or unexpected logging behavior ähnelt.
        /// </summary>
        public static string MAD2023_Description {
            get {
                return ResourceManager.GetString("MAD2023_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid braces in message template ähnelt.
        /// </summary>
        public static string MAD2023_Message {
            get {
                return ResourceManager.GetString("MAD2023_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die InvalidBracesInMessageTemplate ähnelt.
        /// </summary>
        public static string MAD2023_Title {
            get {
                return ResourceManager.GetString("MAD2023_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Named placeholders in the logging message template should not be composed of only numeric characters. ähnelt.
        /// </summary>
        public static string MAD2253_Description {
            get {
                return ResourceManager.GetString("MAD2253_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Named placeholders should not be numeric values ähnelt.
        /// </summary>
        public static string MAD2253_Message {
            get {
                return ResourceManager.GetString("MAD2253_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NamedPlaceholdersShouldNotBeNumeric ähnelt.
        /// </summary>
        public static string MAD2253_Title {
            get {
                return ResourceManager.GetString("MAD2253_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When performing logging, it&apos;s desirable to preserve the structure of the log (including placeholder names) along with the placeholder values. Preserving this information allows for better observability and search in log aggregation and monitoring software. ähnelt.
        /// </summary>
        public static string MAD2254_Description {
            get {
                return ResourceManager.GetString("MAD2254_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template should be a static expression ähnelt.
        /// </summary>
        public static string MAD2254_Message {
            get {
                return ResourceManager.GetString("MAD2254_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TemplateShouldBeStatic ähnelt.
        /// </summary>
        public static string MAD2254_Title {
            get {
                return ResourceManager.GetString("MAD2254_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exceptions should be passed first to the logger method to enhance root cause analysis for an exception by including proper exception processing with the ability to also print stacktraces. ähnelt.
        /// </summary>
        public static string MAD2255_Description {
            get {
                return ResourceManager.GetString("MAD2255_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exceptions should be passed first to the logger method to be able to include the stacktrace in the log. ähnelt.
        /// </summary>
        public static string MAD2255_Message {
            get {
                return ResourceManager.GetString("MAD2255_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ExceptionsShouldBePassedFirst ähnelt.
        /// </summary>
        public static string MAD2255_Title {
            get {
                return ResourceManager.GetString("MAD2255_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die die Beschreibung für MAD2256 enthält.
        /// </summary>
        public static string MAD2256_Description {
            get {
                return ResourceManager.GetString("MAD2256_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avoid inline serialization in log message arguments ähnelt.
        /// </summary>
        public static string MAD2256_Message {
            get {
                return ResourceManager.GetString("MAD2256_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AvoidInlineSerializationInLogArguments ähnelt.
        /// </summary>
        public static string MAD2256_Title {
            get {
                return ResourceManager.GetString("MAD2256_Title", resourceCulture);
            }
        }
    }
}
